version: '3.8'

services:
  nestjs-qr-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - AUTH_TOKEN=${AUTH_TOKEN:-your-secret-bearer-token-here}
      - MAX_FILE_SIZE=10485760
    volumes:
      # Mount .env file if it exists locally
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3004/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qr-api-network

networks:
  qr-api-network:
    driver: bridge